# Generated by Django 6.0.6 on 2026-06-08 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='processed_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
