# Generated by Django 6.0.6 on 2026-06-09 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_fileupload_processed_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
