# Generated by Django 6.0.6 on 2026-06-09 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0003_fileupload_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='document_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
